-- =============================================
-- Quick Data Migration - Copy & Paste in Supabase SQL Editor
-- =============================================

-- Services
INSERT INTO services (id, title, summary, features, created_at)
VALUES
('svc_1', 'Clinic Launch', 'From feasibility study to opening day execution.', '["Market research", "Facility planning", "Staff onboarding"]'::jsonb, NOW()),
('svc_2', 'Digital Transformation', 'Upgrade operations using unified care and admin platforms.', '["EMR workflow design", "Training", "Data dashboards"]'::jsonb, NOW()),
('svc_3', 'Operational Audits', 'Performance, compliance, and patient journey reviews.', '["SOP review", "KPI setup", "Quality improvement plans"]'::jsonb, NOW())
ON CONFLICT (id) DO NOTHING;

-- Doctors
INSERT INTO doctors (id, slug, title, excerpt, description, sector, location, status, cover_image, gallery, details, created_at)
VALUES
('prj_1', 'dr-omar-hassan', 'Dr. Omar Hassan', 'Consultant in internal medicine with 12+ years of clinical practice.', 'Dr. Omar Hassan focuses on comprehensive adult care, chronic disease management, and preventive medicine with evidence-based plans.', 'Internal Medicine', 'Main Clinic - Cairo', 'Available', 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1580281657527-47f249e8f4df?auto=format&fit=crop&w=1000&q=80"]'::jsonb, '["Focuses on hypertension, diabetes, and preventive checkups.", "Provides bilingual consultations (Arabic/English).", "Available Sunday to Thursday from 10:00 AM to 6:00 PM."]'::jsonb, '2026-03-01T10:00:00.000Z'),
('prj_2', 'dr-khan-adel', 'Dr. Khan Adel', 'Dermatology specialist for clinical and cosmetic treatments.', 'Dr. Khan Adel provides diagnosis and treatment for skin, hair, and nail conditions with modern non-invasive procedures.', 'Dermatology', 'North Branch - Alexandria', 'Available', 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80', '["https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=1000&q=80"]'::jsonb, '["Treats acne, eczema, pigmentation, and skin infections.", "Offers laser and minimally invasive cosmetic sessions.", "Available Saturday to Wednesday from 12:00 PM to 8:00 PM."]'::jsonb, '2026-03-10T12:00:00.000Z')
ON CONFLICT (id) DO NOTHING;

-- Blogs
INSERT INTO blogs (id, slug, title, excerpt, content, author, published_at, tags)
VALUES
('blg_1', 'five-signs-your-clinic-needs-a-workflow-redesign', 'Five Signs Your Clinic Needs a Workflow Redesign', 'Long queues and documentation delays are early warning signs that your clinic workflow needs improvement.', 'When clinics grow quickly, the original workflow often fails. Start by tracking bottlenecks in registration, triage, and discharge. Common signs include patient wait times exceeding 30 minutes, staff overtime becoming routine, and frequent miscommunication between departments. A well-designed workflow reduces errors, improves patient satisfaction, and increases staff efficiency.', 'Operations Team', '2026-02-15', '["Operations", "Healthcare", "Workflow"]'::jsonb),
('blg_2', 'importance-of-regular-health-checkups', 'The Importance of Regular Health Checkups', 'Preventive care through regular checkups can detect health issues early when they are most treatable.', 'Regular health checkups are essential for maintaining good health and catching potential problems early. Adults should have a general checkup at least once a year. These visits typically include blood pressure measurement, cholesterol screening, blood glucose tests, and age-appropriate cancer screenings. Early detection of conditions like diabetes, hypertension, and heart disease can significantly improve treatment outcomes and quality of life.', 'Dr. Medical Team', '2026-03-01', '["Preventive Care", "Health Tips", "Wellness"]'::jsonb),
('blg_3', 'managing-diabetes-lifestyle-tips', 'Managing Diabetes: Essential Lifestyle Tips', 'Learn practical strategies to manage diabetes through diet, exercise, and regular monitoring.', 'Diabetes management requires a comprehensive approach combining medication, diet, and lifestyle changes. Key strategies include monitoring blood sugar levels regularly, eating a balanced diet rich in fiber and low in refined sugars, exercising for at least 150 minutes per week, maintaining a healthy weight, and taking medications as prescribed. Regular consultations with your healthcare provider help adjust treatment plans as needed.', 'Internal Medicine Dept.', '2026-03-05', '["Diabetes", "Chronic Disease", "Lifestyle"]'::jsonb),
('blg_4', 'understanding-blood-pressure-readings', 'Understanding Your Blood Pressure Readings', 'What do the numbers mean and why monitoring blood pressure is crucial for heart health.', 'Blood pressure is measured in millimeters of mercury (mmHg) with two numbers: systolic (top) and diastolic (bottom). Normal blood pressure is below 120/80 mmHg. Elevated readings between 120-129/80 indicate elevated blood pressure. Stage 1 hypertension is 130-139/80-89, and Stage 2 is 140/90 or higher. Uncontrolled high blood pressure increases risk of heart attack, stroke, and kidney disease. Regular monitoring and lifestyle modifications can help maintain healthy levels.', 'Cardiology Team', '2026-03-10', '["Heart Health", "Blood Pressure", "Prevention"]'::jsonb),
('blg_5', 'skin-care-tips-for-healthy-skin', 'Dermatologist-Approved Skin Care Tips', 'Simple daily habits that can improve your skin health and prevent common skin problems.', 'Healthy skin starts with consistent care. Dermatologists recommend cleansing your face twice daily with a gentle cleanser, applying sunscreen with SPF 30 or higher every day, moisturizing regularly to maintain skin barrier function, and avoiding excessive sun exposure. For specific concerns like acne, eczema, or pigmentation, consult a dermatologist for personalized treatment. Remember, what works for one person may not work for another.', 'Dermatology Dept.', '2026-03-15', '["Skin Care", "Dermatology", "Health Tips"]'::jsonb),
('blg_6', 'mental-health-awareness-seeking-help', 'Mental Health Awareness: When to Seek Help', 'Recognizing signs of mental health issues and understanding when professional support is needed.', 'Mental health is as important as physical health. Warning signs that indicate you may need professional help include persistent sadness lasting more than two weeks, excessive worry or fear, significant changes in sleep or appetite, difficulty concentrating, withdrawal from social activities, and thoughts of self-harm. Seeking help is a sign of strength, not weakness. Treatment options include therapy, medication, and lifestyle changes. Early intervention leads to better outcomes.', 'Wellness Team', '2026-03-18', '["Mental Health", "Wellness", "Self-Care"]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- News
INSERT INTO news (id, slug, title, excerpt, content, published_at, source)
VALUES
('nws_1', 'sh-med-opens-training-center', 'Sh-Med Opens Regional Training Center', 'A new center focused on practical clinical operations training for healthcare professionals.', 'The training center will support nurses, front-desk teams, and clinic managers with simulation-based modules. The facility features state-of-the-art equipment and experienced instructors who will provide hands-on training in patient care, emergency response, and administrative procedures. This initiative aims to improve healthcare quality across our network.', '2026-03-12', 'Sh-Med Press'),
('nws_2', 'new-pediatric-department-opening', 'New Pediatric Department Opening Next Month', 'Sh-Med expands services with a dedicated pediatric care unit staffed by experienced specialists.', 'We are excited to announce the opening of our new Pediatric Department, designed specifically for the healthcare needs of infants, children, and adolescents. The department will offer routine check-ups, vaccinations, developmental assessments, and treatment for common childhood illnesses. Our team of board-certified pediatricians is committed to providing compassionate, family-centered care.', '2026-03-18', 'Sh-Med Press'),
('nws_3', 'online-appointment-system-upgrade', 'Enhanced Online Appointment Booking System Now Live', 'Patients can now enjoy a faster, more intuitive appointment booking experience with our upgraded system.', 'Our new online appointment system makes scheduling visits easier than ever. Features include real-time availability checking, appointment reminders via SMS and email, the ability to select preferred doctors, and easy rescheduling options. The system is accessible 24/7 from any device, ensuring patients can book appointments at their convenience.', '2026-03-15', 'Technology Update'),
('nws_4', 'free-health-screening-campaign', 'Free Health Screening Campaign Announced for April', 'Community health initiative offers free blood pressure, diabetes, and cholesterol screenings.', 'As part of our commitment to community health, Sh-Med is organizing a free health screening campaign throughout April. The campaign will offer free blood pressure checks, blood glucose testing, cholesterol screening, and BMI assessments. No appointment is necessary. Our healthcare professionals will also provide personalized health advice and referrals when needed.', '2026-03-20', 'Community Health'),
('nws_5', 'telemedicine-services-expansion', 'Telemedicine Services Now Available for All Patients', 'Virtual consultations make healthcare more accessible for patients who cannot visit in person.', 'Sh-Med now offers comprehensive telemedicine services, allowing patients to consult with doctors from the comfort of their homes. Virtual appointments are available for follow-up visits, minor illnesses, prescription refills, and general health consultations. Patients can schedule video calls through our online portal and receive the same quality care as in-person visits.', '2026-03-10', 'Service Update'),
('nws_6', 'new-cardiology-specialist-joins-team', 'Renowned Cardiologist Dr. Sarah Mitchell Joins Sh-Med', 'Award-winning heart specialist brings 20 years of experience to our cardiovascular department.', 'We are pleased to welcome Dr. Sarah Mitchell to our medical team. Dr. Mitchell specializes in preventive cardiology, heart failure management, and cardiac rehabilitation. With over 20 years of experience and numerous awards for excellence in patient care, she will lead our efforts to provide comprehensive heart health services to the community.', '2026-03-08', 'Staff Announcement')
ON CONFLICT (id) DO NOTHING;

-- Site Settings
INSERT INTO site_settings (key, value)
VALUES
('home', '{"headline": "Sh-Med Care Solutions", "subheadline": "We build and operate modern clinic networks with measurable patient outcomes.", "primaryCtaText": "Meet Our Doctors", "primaryCtaLink": "/doctors", "secondaryCtaText": "Contact Us", "secondaryCtaLink": "/contact", "stats": [{"label": "Clinics Managed", "value": "48"}, {"label": "Cities", "value": "11"}, {"label": "Patient Satisfaction", "value": "96%"}]}'::jsonb),
('about', '{"title": "About Sh-Med", "description": "Sh-Med is a healthcare operations agency focused on clinic setup, digital workflows, and patient-centered design.", "mission": "To make premium clinical care accessible through better systems, better facilities, and better teams.", "vision": "To become the region''s most trusted partner for building high-performing care environments.", "values": ["Clinical excellence", "Transparent operations", "Long-term partnerships"]}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Verify
SELECT 'Services' as table_name, COUNT(*) as count FROM services
UNION ALL SELECT 'Doctors', COUNT(*) FROM doctors
UNION ALL SELECT 'Blogs', COUNT(*) FROM blogs
UNION ALL SELECT 'News', COUNT(*) FROM news
UNION ALL SELECT 'Site Settings', COUNT(*) FROM site_settings;
